- project:
    templates:
      - publish-openstack-sphinx-docs
      - periodic-stable-jobs
      - check-requirements
      - release-notes-jobs
    check:
      jobs:
        - openstack-tox-pep8
        - legacy-swift-dsvm-functional:
            irrelevant-files:
              - ^api-ref/.*$
              - ^doc/.*$
              - ^install-guide/.*$
              - ^releasenotes/.*$
              - ^test/unit/.*$
        - legacy-swift-dsvm-functional-identity-v3-only:
            voting: false
            irrelevant-files:
              - ^api-ref/.*$
              - ^doc/.*$
              - ^install-guide/.*$
              - ^releasenotes/.*$
              - ^test/unit/.*$
        - legacy-tempest-dsvm-neutron-full:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^api-ref/.*$
              - ^doc/.*$
              - ^install-guide/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^test/unit/.*$
        - neutron-grenade:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^api-ref/.*$
              - ^doc/.*$
              - ^install-guide/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^test/unit/.*$
    gate:
      jobs:
        - openstack-tox-pep8
        - legacy-swift-dsvm-functional:
            irrelevant-files:
              - ^api-ref/.*$
              - ^doc/.*$
              - ^install-guide/.*$
              - ^releasenotes/.*$
              - ^test/unit/.*$
        - legacy-tempest-dsvm-neutron-full:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^api-ref/.*$
              - ^doc/.*$
              - ^install-guide/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^test/unit/.*$
        - neutron-grenade:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^api-ref/.*$
              - ^doc/.*$
              - ^install-guide/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^test/unit/.*$
    post:
      jobs:
        - openstack-tox-cover
        - publish-openstack-python-branch-tarball
    experimental:
      jobs:
        - legacy-tempest-dsvm-neutron-pg-full:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^api-ref/.*$
              - ^doc/.*$
              - ^install-guide/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^test/unit/.*$
